//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterRecovery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DisasterRecoveryEntities : DbContext
    {
        public DisasterRecoveryEntities()
            : base("name=DisasterRecoveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobList> JobLists { get; set; }
        public virtual DbSet<SiteLocation> SiteLocations { get; set; }
        public virtual DbSet<SubContractor> SubContractors { get; set; }
        public virtual DbSet<TimeCard> TimeCards { get; set; }
        public virtual DbSet<TimeCardDetail> TimeCardDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
