//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobList()
        {
            this.TimeCardDetails = new HashSet<TimeCardDetail>();
        }
    
        public int IdJobList { get; set; }
        public int IdSubContractor { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> MaxHour { get; set; }
        public Nullable<int> LaborStatus { get; set; }
    
        public virtual SubContractor SubContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeCardDetail> TimeCardDetails { get; set; }
    }
}
