//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterRecovery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeCard()
        {
            this.TimeCardDetails = new HashSet<TimeCardDetail>();
        }
    
        public int IdTimeCard { get; set; }
        public int SiteID { get; set; }
        public int IdSubContractor { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TimeStatus { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public int IdUser { get; set; }
    
        public virtual SiteLocation SiteLocation { get; set; }
        public virtual SubContractor SubContractor { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeCardDetail> TimeCardDetails { get; set; }
    }
}
